In [14]:
import pandas as pd
import numpy as np
import re

def clean_data(df):
    # Keep only numeric characters in the ProductID column
    df['ProductID'] = df['ProductID'].apply(lambda x: re.sub(r'\D', '', str(x)))
    
    # replace rows with nan  where 'ProductName' is 'INVALID'
    df['ProductName'].replace('INVALID', np.nan, inplace=True)
    
   # replace rows with nan  where 'Discount' is 'INVALID'
    df['Discount'].replace('INVALID', np.nan, inplace=True)
    
    
    # Fill NaN values in 'ProductName' and 'Category' columns based on mode
    df['ProductName'] = df.groupby('ProductID')['ProductName'].transform(lambda x: x.fillna(x.mode().iloc[0]))
    df['Category'] = df.groupby('ProductName')['Category'].transform(lambda x: x.fillna(x.mode().iloc[0]))
    
    # Replace empty strings with NaN in 'ProductID' column
    df['ProductID'].replace('', np.nan, inplace=True)
    
    # Fill NaN values in 'ProductID'  columns based on mode
    df1['ProductID'] = df1.groupby('ProductName')['ProductID'].transform(lambda x: x.fillna(x.mode().iloc[0]))
    
    return df

def drop_zero_values(df):
    # Identify and drop rows with zero values in Price, Quantity, and TotalPrice
    condition_price = (df['Price'] == 0) | (df['TotalPrice'] == 0)
    condition_quantity = (df['Quantity'] == 0) | (df['TotalPrice'] == 0)
    
    dropped_price_quantity = df[(condition_price) & (condition_quantity)].copy()
    df = df[~(condition_price) & ~(condition_quantity)]
    
    return df, dropped_price_quantity

# Example usage:

data = pd.read_csv(r"C:/Users/Admin/Downloads/Shopee_retaiset_conf.csv")
data_fm=pd.DataFrame(data)

# Clean the data
cleaned_data = clean_data(data_fm.copy())

# Drop zero values in specified columns
cleaned_data_no_zeros, dropped_zeros = drop_zero_values(cleaned_data.copy())#Calling cleaned_data.copy() 
#ensures that the original DataFrame cleaned_data remains unaltered during the process of dropping zero values.
#
#This variable will hold the DataFrame after dropping rows with zero values.
df1=pd.DataFrame(cleaned_data_no_zeros)
df2=pd.DataFrame(dropped_zeros)

# Display the results
print("Cleaned DataFrame:")
print(df1)

print("\nDropped Rows with zero values in Price, Quantity, and TotalPrice:")
print(df2)

print("\nOriginal, Uncleaned DataFrame:")
print(data_fm)

Cleaned DataFrame:
    ProductID ProductName    Price     Category Discount  Quantity  TotalPrice
1           1  Headphones   126.36  Electronics     0.07         3      379.08
2           1  Headphones   207.21  Electronics      NaN        87    18027.27
3           0  Television  1045.60  Electronics     0.03        49    51234.40
4           2       Phone   520.46  Electronics     0.45        28    14572.88
5           1  Headphones    82.30  Electronics     0.02        48     3950.40
..        ...         ...      ...          ...      ...       ...         ...
994         4     T-Shirt    24.54     Clothing     0.15        28      687.12
996         0  Television  1135.04  Electronics     0.02        81    91938.24
997         6      Laptop  1314.22  Electronics     0.25        28    36798.16
998         2       Phone   271.29  Electronics     0.14        17     4611.93
999         1  Headphones   142.54  Electronics     0.24        11     1567.94

[823 rows x 7 columns]

Dropped Rows with zero values in Price, Quantity, and TotalPrice:
    ProductID ProductName   Price     Category Discount  Quantity  TotalPrice
0           0  Television    0.00  Electronics     0.19        62         0.0
7           3  Toothpaste    0.00    Groceries      NaN        47         0.0
9           4     T-Shirt    0.00     Clothing     0.35        86         0.0
13          0  Television  896.34  Electronics     0.29         0         0.0
16          0  Television    0.00  Electronics      NaN        79         0.0
..        ...         ...     ...          ...      ...       ...         ...
985         4     T-Shirt    0.00     Clothing     0.46        16         0.0
986         6      Laptop  587.23  Electronics     0.32         0         0.0
989         0  Television    0.00  Electronics     0.03         3         0.0
993         5        Oven    0.00    HomeDecor     0.29        53         0.0
995         4     T-Shirt   23.15     Clothing     0.32         0         0.0

[177 rows x 7 columns]

Original, Uncleaned DataFrame:
    ProductID ProductName    Price     Category Discount  Quantity  TotalPrice
0           0  Television     0.00  Electronics     0.19        62        0.00
1           1  Headphones   126.36  Electronics     0.07         3      379.08
2          1!  Headphones   207.21  Electronics      NaN        87    18027.27
3          0*  Television  1045.60  Electronics     0.03        49    51234.40
4           2     INVALID   520.46  Electronics     0.45        28    14572.88
..        ...         ...      ...          ...      ...       ...         ...
995        4*     T-Shirt    23.15     Clothing     0.32         0        0.00
996         0  Television  1135.04  Electronics     0.02        81    91938.24
997         6      Laptop  1314.22  Electronics     0.25        28    36798.16
998         2       Phone   271.29  Electronics     0.14        17     4611.93
999         1  Headphones   142.54  Electronics     0.24        11     1567.94

[1000 rows x 7 columns]